
import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  lab_name: { en: "Zhejiang University of Technology", zh: "浙江工业大学" },
  lab_details: { en: "Laboratory Details", zh: "实验室详情" },
  lab_overview: { en: "Overview", zh: "概况" },
  lab_team: { en: "Research Team", zh: "科研团队" },
  lab_research: { en: "Research Areas", zh: "研究方向" },
  lab_publications: { en: "Publications", zh: "学术成果" },
  lab_resources: { en: "Resources & Code", zh: "资源与代码" },
  typhoon_estimation: { en: "Typhoon Estimation", zh: "台风强度评估" },
  idol_viz: { en: "IDOL", zh: "IDOL" },
  cloud_pred: { en: "Cloud Prediction", zh: "云系演变预测" },
  rainfall_forecasting: { en: "Rainfall Forecasting", zh: "降水概率预报" },
  active_case: { en: "Active Case Selection", zh: "台风场次选择" },
  timeline: { en: "Timeline", zh: "时间轴" },
  metrics: { en: "Comparison Line Chart", zh: "对比折线图" },
  ground_truth: { en: "Ground Truth", zh: "实测强度" },
  prediction: { en: "IDOL Prediction", zh: "IDOL 模型预测" },
  wind_speed: { en: "Maximum Wind Speed (m/s)", zh: "最大风速 (m/s)" },
  pressure: { en: "Central Pressure (hPa)", zh: "中心气压 (hPa)" },
  inner_radius_label: { en: "Inner Wind Radius: Radius of Maximum Wind (RMW)", zh: "内风圈：最大风半径 RMW" },
  outer_radius_label: { en: "Outer Wind Radius: 34-kt Wind Radius (R34)", zh: "外风圈：34kt 风圈半径 R34" },
  cloud_view: { en: "Satellite Cloud Imagery", zh: "实时卫星云图" },
  satellite_ir: { en: "Himawari-8 IR (Raw)", zh: "葵花8号红外云图" },
  error_metric: { en: "RMSE Error:", zh: "均方根误差 (RMSE):" },
  zoom_hint: { en: "Scroll to zoom", zh: "滚动缩放地图" },
  physics_prior: { en: "Physics Prior Module", zh: "物理先验模块" },
  real_time_params: { en: "Real-time Parameters", zh: "实时观测参数" },
  model_comparison: { en: "Model Comparison", zh: "参数估算对比" },
  traditional_method: { en: "Ground Truth", zh: "真值" },
  idol_model: { en: "IDOL", zh: "IDOL模型" },
  lat: { en: "Lat", zh: "纬度" },
  lng: { en: "Lng", zh: "经度" },
  r_inner: { en: "RMW", zh: "最大风半径" },
  r_outer: { en: "R34 (34kt)", zh: "34节风圈" },
  rmw_short: { en: "RMW", zh: "最大风半径" },
  r34_short: { en: "R34", zh: "34节风圈" },
  physics_desc: {
    en: "AI estimation constrained by Holland's gradient wind balance and pressure-wind relationship priors.",
    zh: "AI强度评估通过Holland梯度风平衡及气压-风速关系先验进行约束。"
  },
  physics_param_r: { en: "Radial distance", zh: "径向距离" },
  physics_param_B: { en: "Shape parameter", zh: "形状参数" },
  physics_param_pn: { en: "Ambient pressure", zh: "环境气压" },
  physics_param_pc: { en: "Central pressure", zh: "中心气压" },
  physics_param_pr: { en: "Pressure at r", zh: "r处气压" },
  physics_param_A: { en: "Scale parameter", zh: "尺度参数" },
  wind_label_short: { en: "MAX WIND", zh: "最大风速" },
  pressure_label_short: { en: "CENT PRES", zh: "中心气压" },
  wind_radii: { en: "Wind Radii (km): RMW / R34", zh: "风圈半径 (km)：最大风半径 / 34节风圈" },
  holland_model: { en: "Holland Wind Field Model", zh: "霍兰德风场模型" },
  analysis_dashboard: { en: "Analysis Dashboard", zh: "分析控制台" },
  prev_page: { en: "Previous", zh: "上一页" },
  next_page: { en: "Next", zh: "下一页" },
  page_info: { en: "Page {current} of {total}", zh: "第 {current} 页，共 {total} 页" },



  // --- CloudSeer 新增词条 ---
  cloudseer_scene: { en: "Cloud Scene Selection", zh: "云系场景选择" },
  typhoon_cloud: { en: "Typhoon Cloud System", zh: "台风云系" },
  convection_cloud: { en: "Severe Convection", zh: "强对流云系" },
  front_cloud: { en: "Frontal Cloud System", zh: "锋面云系" },
  cloud_timeline: { en: "Nowcasting Timeline (6h Window)", zh: "预报时间轴 (6小时)" },
  past_input: { en: "Past 3h (Input)", zh: "过去3小时 (输入)" },
  future_pred: { en: "Future 3h (Prediction)", zh: "未来3小时 (预报)" },
  band_selection: { en: "Spectral Band", zh: "光谱波段" },
  model_comparison_cloud: { en: "Model Comparison", zh: "模型对比" },
  motion_vector_field: { en: "Atmospheric Motion Field", zh: "大气运动矢量场" },
  adcmp_branch: { en: "ADCMP Branch", zh: "ADCMP 分支" },
  fgtp_branch: { en: "FGTP Branch", zh: "FGTP 分支" },
  gate_fusion: { en: "Gate Fusion", zh: "门控融合" },
  physics_constraints: { en: "Atmospheric Dynamics Constraints", zh: "大气动力学约束" },
  advection: { en: "Advection Consistency", zh: "平流一致性" },
  shear_stretch: { en: "Shear-Stretch Balance", zh: "剪切-拉伸平衡" },
  vorticity: { en: "Vorticity Control", zh: "涡度控制" },
  cloudseer_metrics: { en: "Nowcasting Metrics", zh: "预报精度指标" },
  mse: { en: "MSE", zh: "均方误差" },
  mae: { en: "MAE", zh: "平均绝对误差" },
  psnr: { en: "PSNR (dB)", zh: "峰值信噪比" },
  ssim: { en: "SSIM", zh: "结构相似性" },
  cloudseer_arch: { en: "CloudSeer Architecture", zh: "CloudSeer 架构" },
  motion_texture_decouple: { en: "Motion-Texture Decoupling", zh: "运动-纹理解耦" },
  gt_cloud: { en: "Ground Truth", zh: "真实云图" },
  cloudseer_pred: { en: "CloudSeer Prediction", zh: "CloudSeer 预报" },





};
